# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- dev

pool:
  name: Azure Pipelines
steps:
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.SourcesDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true


- task: Veracode@3
  inputs:
    ConnectionDetailsSelection: 'Endpoint'
    AnalysisService: 'VeraCode'
    veracodeAppProfile: '$(system.teamProject)'
    version: '$(build.buildNumber)'
    filepath: '$(Build.SourcesDirectory)/$(Build.BuildId).zip'
    createProfile: true
    maximumWaitTime: '360'


#- task: SonarQubePrepare@5
# inputs:
 #  SonarQube: 'sonar'
  #  scannerMode: 'CLI'
  #  configMode: 'manual'
   # cliProjectKey: 'beta.template.webtools.website'
    #cliProjectName: 'beta.template.webtools.website'
   # cliSources: '$(Build.SourcesDirectory)'
#- task: SonarQubeAnalyze@5
    
#- task: SonarQubePublish@5
  #inputs:
   # pollingTimeoutSec: '300'
